### ISSUE TITLE
Error on using heap command.

### ISSUE THREAD

**Issue by mjnovice** [rogerhu/gdb-heap#17]
I am trying to use the gdb-heap for getting the heap memory allocation of my program. I am doing this, "gdb -p 3108 -x ~/Documents/gdb-heap-commands",
after following the instructions out here. Then I did heap, and I got this, "Python Exception <type 'exceptions.TypeError'> iter() returned non-iterator of type 'ProgressNotifier': 
Error occurred in Python command: iter() returned non-iterator of type 'ProgressNotifier'"

**Comment by glic3rinu** [comment]
I'm getting same error here

```
(gdb) heap
Python Exception <type 'exceptions.TypeError'> iter() returned non-iterator of type 'ProgressNotifier': 
Error occurred in Python command: iter() returned non-iterator of type 'ProgressNotifier'
```

**Comment by rogerhu** [comment]
Yeah there seems to be a bug after upgrading to using the Python 3 interpreter.  You can comment out the iter() or help issue a PR to fix...thanks!

**Comment by rogerhu** [comment]
This should be fixed now?
