### ISSUE TITLE
Change README to stop saying "forked from..."

### ISSUE THREAD

**Issue by tromey** [rogerhu/gdb-heap#23]
David Malcolm told me on irc that this is the canonical repository for gdb-heap now.  I think the README should change to stop saying that it is a fork of the fedora hosted repository (which isn't available any more anyway...).

**Comment by davidmalcolm** [comment]
I haven't had time to work on gdb-heap for years, so this may as well be the official repo as far as I'm concerned - though this one seems inactive also (just fewer years inactive...)

**Comment by rogerhu** [comment]
Yeah I upgraded it last to Python 3...haven't used it as much but hoping it still works!  Please let me know.

**Comment by rogerhu** [comment]
Fixed README.md (https://github.com/rogerhu/gdb-heap/commit/e60dc78c515c13fbaeffc0f207ae84aee1d4caec).  

Please feel free to issue any pull requests!
